# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      prisma:
        patterns:
          - '@prisma/*'
          - prisma
      eslint:
        patterns:
          - eslint*
          - '@eslint/*'
          - typescript-eslint
      types:
        patterns:
          - '@types/*'

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
